### ISSUE TITLE
Come up with concrete examples of what design optimisation actually looks like using battery models

### ISSUE THREAD

**Issue by davidhowey** [pybop-team/PyBOP#2]
To make the challenge more tangible we should think of some examples of how battery models might be optimised from a design point of view and code these up in PyBOP. [Example previous study](https://doi.org/10.1016/j.energy.2022.125966)

**Comment by NicolaCourtier** [comment]
To date, we have added two [example design costs](https://github.com/pybop-team/PyBOP/blob/develop/pybop/costs/design_costs.py): one for the gravimetric energy density and another for the volumetric energy density. These are based on the [example study](https://doi.org/10.1016/j.energy.2022.125966) mentioned above.

I believe our [gravimetric energy density example](https://github.com/pybop-team/PyBOP/blob/develop/examples/scripts/spme_max_energy.py) addresses one of @scro2542's suggestions, as it optimises the energy density calculated from a CC discharge with respect to geometric parameters such as electrode thickness and particle radius.

Suggestions of further design optimisation examples are very welcome, although it is worth noting that optimising manufacturing parameters is currently out-of-scope due to the lack of manufacturing models.

**Comment by BradyPlanden** [comment]
Closing this issue as @NicolaCourtier mentions above. Feel free to open a new issue with more specific outcomes.
