### ISSUE TITLE
[Bug]: Update the notebooks

### ISSUE THREAD

**Issue by BradyPlanden** [pybop-team/PyBOP#261]
### Python Version

N/A

### Describe the bug

Notebooks mostly seem up to date, but there are a [few errors](https://github.com/pybop-team/PyBOP/blob/develop/examples/notebooks/spm_electrode_design.ipynb).

There is a further question on whether we should enable `--overwrite` within the `nox -s notebooks` session to avoid this in the future. Any thoughts @agriyakhetarpal?

### Steps to reproduce the behaviour

N/A

**Comment by agriyakhetarpal** [comment]
Thanks @BradyPlanden, actually I haven't got very far with #173 yet – maybe I'll have a concrete answer to this question once I have a PR for that and we can discuss this there. AFAIR, one of the reasons we did not go ahead with the `--overwrite` flag with PyBaMM was because that doing so could add more changes to files in the working tree and therefore could create some clutter with version control during local development – though, this also came with the fact that PyBaMM had/has almost seventy notebooks to test, but PyBOP does not have as many.
