### ISSUE TITLE
[Bug]: Contact resistance has no influence on impedance

### ISSUE THREAD

**Issue by noelhallemans** [pybop-team/PyBOP#416]
### Python Version

3.12.4

### Describe the bug

When evaluating the impedance, varying the parameter "Contact resistance [Ohm]" has no effect on the impedance while it should.

### Steps to reproduce the behaviour

Run prediction = problem.evaluate(params) with params containing "Contact resistance [Ohm]".

**Comment by NicolaCourtier** [comment]
In order to use the `"Contact resistance [Ohm]"` parameter in a PyBaMM model, you need to enable this option when creating the model, e.g. using:
`model = pybop.lithium_ion.SPM(options={"contact resistance": "true"})`
Then set the value of this parameter using:
`parameter_set["Contact resistance [Ohm]"] = 0.02`

@BradyPlanden let's add this to the example in #405.
